# Generated by Django 4.2.6 on 2023-10-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='место, в котором необходимо выполнять привычку')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время, когда необходимо выполнять привычку')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Действие')),
                ('is_enjoyable', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('frequency', models.IntegerField(choices=[(1, 'Ежедневная'), (7, 'Еженедельная')], default=1)),
                ('reward', models.CharField(blank=True, max_length=255, verbose_name='награда')),
                ('estimated_time', models.PositiveIntegerField(default=0, help_text='Время в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.habit', verbose_name='связи')),
            ],
        ),
    ]
